---
title: "4-H National Mentoring Program"
author: "JIHOON WOO"
date: "March 7, 2019"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

## Packages and working directory
```{r, echo=FALSE}
if (!require("ggplot2")){
    install.packages("ggplot2", repos = "http://cran.us.r-project.org")
    require("ggplot2")
}
if (!require("dplyr")){
    install.packages("dplyr")
    require("dplyr")
}
if (!require("car")){
    install.packages("car")
    require("car")
}
if (!require("readxl")){
    install.packages("readxl")
    require("readxl")
}
if (!require("nnet")){
    install.packages("nnet")
    require("nnet")
}

```

# 2017 analysis
```{r, echo=TRUE}
pre17 <- read_xlsx("C:/Users/Ji Hoon/Desktop/Data Analysis/2017/WI pre NMP7raw_cleansed.xlsx")
post17 <- read_xlsx("C:/Users/Ji Hoon/Desktop/Data Analysis/2017/Wisconsin_FinalRaw NMP7_cleansed.xlsx")

pre17 <- pre17[,-c(1:2)] %>% filter(pre17$IDENTIFY != "#N/A") # removing vlookup columns & N=53 matched sample size
post17 <- post17[-c(1:2)] %>% filter(post17$IDENTIFY != "#N/A") # matching paired sample!
a1 <- pre17$IDENTIFY %in% post17$IDENTIFY # 50
a2 <- post17$IDENTIFY %in% pre17$IDENTIFY # 50 
a3 <- with(pre17, IDENTIFY[a1 %in% TRUE])
a4 <- with(post17, IDENTIFY[a2 %in% TRUE])
a3[duplicated(a3)] # 147144
a4[duplicated(a4)] # 136861 are duplicates!
a3 <- a3[a3!= 147144 & a3!= 136861] 
a4 <- a4[a4!= 147144 & a4!= 136861] # finally we have 45 paired data
pre17 <- filter(pre17, pre17$IDENTIFY %in% a3) %>% arrange(IDENTIFY)
post17 <- filter(post17, post17$IDENTIFY %in% a4) %>% arrange(IDENTIFY)

sum(is.na(pre17$IDENTIFY)) # double check to make sure that there is no missing-out
factor(pre17$Q91_1)
freq1 <- table(pre17$Q91_1)
mean1 <- mean(pre17$Q91_1) #5.04
med1 <- median(pre17$Q91_1) # testing with median to see how it results in = 5

sum(is.na(post17$Q1)) # there exists NA value
mean2 <- mean(post17$Q1, na.rm = TRUE) # ignoring NA to 0, than 5.682
med2 <- median(post17$Q1, na.rm = TRUE) # 6
factor(post17$Q1) # No huge difference between 0 and mean value for NA
freq2 <- table(post17$Q1)
# After data cleanse, even though normality does not follow, mean of 2 groups follow CLT
par(mfrow=c(1,2))
barplot(freq1, main = "Pre17 Q1 barplot",
        xlab = "Scale", ylab = "Frequency")
barplot(freq2, main = "Post 17 Q1 barplot",
        xlab =  "Scale", ylab = "Frequency")
dev.off()
boxplot(pre17$Q91_1,post17$Q1, main= "Mean pre17 vs. post17", xlab =  "Distribution", ylab = "Scale")

# Running paired t-test if there is any significance
result1 <- t.test(pre17$Q91_1, post17$Q1, paired = TRUE) # .065 but it seems like it has a significance
result1.1 <- t.test(median(pre17$Q91_1),median(post17$Q1), paired = TRUE)

# Let's check normality
d1 <- with(pre17,Q91_1) 
qqPlot(d1) # qqplot, does not hold normaility
shapiro.test(d1) # p-value is too small, it does not follow normaility
d2 <- with(post17,Q1)
qqPlot(d2) # qqplot does not hold normaility either
shapiro.test(d2) # this one either  
# seems like if does not follow normaility, let's try Non-parametric test to see how much it is different from the parametric paired t-test
wilcox.test(pre17$Q91_1,post17$Q1, paired = TRUE, exact = FALSE) # .084

```

## Results
```{r,echo=TRUE}
result2 <- t.test(pre17$Q91_2, post17$Q2, paired = TRUE) # .074
wilcox.test(pre17$Q91_2,post17$Q2, paired = TRUE, exact = FALSE) # .078

result3 <- t.test(pre17$Q91_3, post17$Q3, paired = TRUE) # .146
wilcox.test(pre17$Q91_3,post17$Q3, paired = TRUE, exact = FALSE) # .148

result4 <- t.test(pre17$Q91_4, post17$Q4, paired = TRUE) # .367
wilcox.test(pre17$Q91_4,post17$Q4, paired = TRUE, exact = FALSE) # .447

result5 <- t.test(pre17$Q91_5, post17$Q5, paired = TRUE) # .049!!
wilcox.test(pre17$Q91_5,post17$Q5, paired = TRUE, exact = FALSE) # .061!!

result6 <- t.test(pre17$Q91_6, post17$Q6, paired = TRUE) # .263
wilcox.test(pre17$Q91_6,post17$Q6, paired = TRUE, exact = FALSE) # .195

result7 <- t.test(pre17$Q91_7, post17$Q7, paired = TRUE) # .465
wilcox.test(pre17$Q91_7,post17$Q7, paired = TRUE, exact = FALSE) # .313

result8 <- t.test(pre17$Q91_8, post17$Q8, paired = TRUE) # .748
wilcox.test(pre17$Q91_8,post17$Q8, paired = TRUE, exact = FALSE) # .664

result9 <- t.test(pre17$Q91_9, post17$Q9, paired = TRUE) # .047!!
wilcox.test(pre17$Q91_9,post17$Q9, paired = TRUE, exact = FALSE) # .037!!

result10 <- t.test(pre17$Q91_10, post17$Q10, paired = TRUE) # .056!!
wilcox.test(pre17$Q91_10,post17$Q10, paired = TRUE, exact = FALSE) # .056!!

result11 <- t.test(pre17$Q91_11, post17$Q11, paired = TRUE) # .008!!
wilcox.test(pre17$Q91_11,post17$Q11, paired = TRUE, exact = FALSE) # .008!!

result12 <- t.test(pre17$Q91_12, post17$Q12, paired = TRUE) # .058!!
wilcox.test(pre17$Q91_12,post17$Q12, paired = TRUE, exact = FALSE) # .035!!

```
If we have more samples, there might be some questions that we were able to reject the null

## Multinomial Categorical Analysis
## Demographics: Gender
```{r,echo=TRUE}
# Gender t-test
gender1 <- with(pre17,table(Q91_1,Gender))
colnames(gender1) <- c("Female","Male","Other")
gender2 <- with(post17,table(Q1, Gender))
colnames(gender2) <- c("Female","Male","Other")

pre17.female <- filter(pre17,pre17$Gender == 1) %>% arrange(IDENTIFY) # 19
post17.female <- filter(post17,post17$Gender == 1) %>% arrange(IDENTIFY) # 20, sample sizes do not mach each other
pre17.female$IDENTIFY %in% post17.female$IDENTIFY
post17.female$IDENTIFY %in% pre17.female$IDENTIFY # ID number "200066" does not exist in pre17 IDENTIFY

row.to.keep <- post17.female$IDENTIFY[post17.female$IDENTIFY != 200066]

post17.female <- filter(post17.female, post17.female$IDENTIFY %in% row.to.keep) # N=19

par(mfrow=c(1,2))
t1 <- table(pre17.female$Q91_1); t2 <- table(post17.female$Q1)
barplot(t1, main ="Female pre17"); barplot(t2, main= "Female post17")
t.test(pre17.female$Q91_1, post17.female$Q1, paired = TRUE) # sample size is small. p= .8
wilcox.test(pre17.female$Q91_1, post17.female$Q1, paired = TRUE, exact = FALSE) # .79

pre17.male <- filter(pre17,pre17$Gender == 2) %>% arrange(IDENTIFY)
post17.male <- filter(post17,post17$Gender == 2) %>% arrange(IDENTIFY)

row.to.keep2 <- pre17.male$IDENTIFY[pre17.male$IDENTIFY %in% post17.male$IDENTIFY]
row.to.keep3 <- post17.male$IDENTIFY[post17.male$IDENTIFY %in% pre17.male$IDENTIFY]

t3 <- table(pre17.male$Q91_1); t4 <- table(post17.male$Q1)
barplot(t3, main ="Male pre17"); barplot(t4, main= "Male post17")
pre17.male <- filter(pre17.male, IDENTIFY %in% row.to.keep2) # 19
post17.male <- filter(post17.male, IDENTIFY %in% row.to.keep3) # 19
t.test(pre17.male$Q91_1, post17.male$Q1, paired = TRUE) #0.01
wilcox.test(pre17.male$Q91_1, post17.male$Q1, paired = TRUE, exact = FALSE) # 0.019

# Chi-squared test to find the association between variables



# Multinomial logistic regression
pre17 <- pre17 %>% 
    mutate(Q91_1 = as.factor(Q91_1),
           Age = as.factor(Age),
           Gender = as.factor(Gender),
           Race = as.factor(Race))
multinomModel <- multinom(Q91_1~Age+Gender+Race,data = pre17)

```

